//! GENERATED by the kind list in this file's sibling script; every Prism node kind routes to its family module.

use ruby_prism::Node;

use super::{Formatter, assign, calls, control, defs, literals, patterns, strings};

impl Formatter<'_> {
    pub(super) fn dispatch(&mut self, node: &Node<'_>) {
        match node {
            Node::ProgramNode { .. } => self.program(&node.as_program_node().expect("kind")),
            Node::StatementsNode { .. } => {
                self.statements(&node.as_statements_node().expect("kind"));
            }
            Node::MissingNode { .. } => self.unsupported("MissingNode", &node.location()),
            Node::AliasGlobalVariableNode { .. } => {
                defs::alias_global_variable_node(self, &node.as_alias_global_variable_node().expect("kind"))
            }
            Node::AliasMethodNode { .. } => defs::alias_method_node(self, &node.as_alias_method_node().expect("kind")),
            Node::AlternationPatternNode { .. } => {
                patterns::alternation_pattern_node(self, &node.as_alternation_pattern_node().expect("kind"))
            }
            Node::AndNode { .. } => control::and_node(self, &node.as_and_node().expect("kind")),
            Node::ArgumentsNode { .. } => calls::arguments_node(self, &node.as_arguments_node().expect("kind")),
            Node::ArrayNode { .. } => calls::array_node(self, &node.as_array_node().expect("kind")),
            Node::ArrayPatternNode { .. } => {
                patterns::array_pattern_node(self, &node.as_array_pattern_node().expect("kind"))
            }
            Node::AssocNode { .. } => calls::assoc_node(self, &node.as_assoc_node().expect("kind")),
            Node::AssocSplatNode { .. } => calls::assoc_splat_node(self, &node.as_assoc_splat_node().expect("kind")),
            Node::BackReferenceReadNode { .. } => {
                literals::back_reference_read_node(self, &node.as_back_reference_read_node().expect("kind"))
            }
            Node::BeginNode { .. } => control::begin_node(self, &node.as_begin_node().expect("kind")),
            Node::BlockArgumentNode { .. } => {
                calls::block_argument_node(self, &node.as_block_argument_node().expect("kind"))
            }
            Node::BlockLocalVariableNode { .. } => {
                defs::block_local_variable_node(self, &node.as_block_local_variable_node().expect("kind"))
            }
            Node::BlockNode { .. } => calls::block_node(self, &node.as_block_node().expect("kind")),
            Node::BlockParameterNode { .. } => {
                defs::block_parameter_node(self, &node.as_block_parameter_node().expect("kind"))
            }
            Node::BlockParametersNode { .. } => {
                defs::block_parameters_node(self, &node.as_block_parameters_node().expect("kind"))
            }
            Node::BreakNode { .. } => control::break_node(self, &node.as_break_node().expect("kind")),
            Node::CallAndWriteNode { .. } => {
                assign::call_and_write_node(self, &node.as_call_and_write_node().expect("kind"))
            }
            Node::CallNode { .. } => calls::call_node(self, &node.as_call_node().expect("kind")),
            Node::CallOperatorWriteNode { .. } => {
                assign::call_operator_write_node(self, &node.as_call_operator_write_node().expect("kind"))
            }
            Node::CallOrWriteNode { .. } => {
                assign::call_or_write_node(self, &node.as_call_or_write_node().expect("kind"))
            }
            Node::CallTargetNode { .. } => assign::call_target_node(self, &node.as_call_target_node().expect("kind")),
            Node::CapturePatternNode { .. } => {
                patterns::capture_pattern_node(self, &node.as_capture_pattern_node().expect("kind"))
            }
            Node::CaseMatchNode { .. } => patterns::case_match_node(self, &node.as_case_match_node().expect("kind")),
            Node::CaseNode { .. } => control::case_node(self, &node.as_case_node().expect("kind")),
            Node::ClassNode { .. } => defs::class_node(self, &node.as_class_node().expect("kind")),
            Node::ClassVariableAndWriteNode { .. } => {
                assign::class_variable_and_write_node(self, &node.as_class_variable_and_write_node().expect("kind"))
            }
            Node::ClassVariableOperatorWriteNode { .. } => assign::class_variable_operator_write_node(
                self,
                &node.as_class_variable_operator_write_node().expect("kind"),
            ),
            Node::ClassVariableOrWriteNode { .. } => {
                assign::class_variable_or_write_node(self, &node.as_class_variable_or_write_node().expect("kind"))
            }
            Node::ClassVariableReadNode { .. } => {
                literals::class_variable_read_node(self, &node.as_class_variable_read_node().expect("kind"))
            }
            Node::ClassVariableTargetNode { .. } => {
                assign::class_variable_target_node(self, &node.as_class_variable_target_node().expect("kind"))
            }
            Node::ClassVariableWriteNode { .. } => {
                assign::class_variable_write_node(self, &node.as_class_variable_write_node().expect("kind"))
            }
            Node::ConstantAndWriteNode { .. } => {
                assign::constant_and_write_node(self, &node.as_constant_and_write_node().expect("kind"))
            }
            Node::ConstantOperatorWriteNode { .. } => {
                assign::constant_operator_write_node(self, &node.as_constant_operator_write_node().expect("kind"))
            }
            Node::ConstantOrWriteNode { .. } => {
                assign::constant_or_write_node(self, &node.as_constant_or_write_node().expect("kind"))
            }
            Node::ConstantPathAndWriteNode { .. } => {
                assign::constant_path_and_write_node(self, &node.as_constant_path_and_write_node().expect("kind"))
            }
            Node::ConstantPathNode { .. } => {
                literals::constant_path_node(self, &node.as_constant_path_node().expect("kind"))
            }
            Node::ConstantPathOperatorWriteNode { .. } => assign::constant_path_operator_write_node(
                self,
                &node.as_constant_path_operator_write_node().expect("kind"),
            ),
            Node::ConstantPathOrWriteNode { .. } => {
                assign::constant_path_or_write_node(self, &node.as_constant_path_or_write_node().expect("kind"))
            }
            Node::ConstantPathTargetNode { .. } => {
                assign::constant_path_target_node(self, &node.as_constant_path_target_node().expect("kind"))
            }
            Node::ConstantPathWriteNode { .. } => {
                assign::constant_path_write_node(self, &node.as_constant_path_write_node().expect("kind"))
            }
            Node::ConstantReadNode { .. } => {
                literals::constant_read_node(self, &node.as_constant_read_node().expect("kind"))
            }
            Node::ConstantTargetNode { .. } => {
                assign::constant_target_node(self, &node.as_constant_target_node().expect("kind"))
            }
            Node::ConstantWriteNode { .. } => {
                assign::constant_write_node(self, &node.as_constant_write_node().expect("kind"))
            }
            Node::DefNode { .. } => defs::def_node(self, &node.as_def_node().expect("kind")),
            Node::DefinedNode { .. } => control::defined_node(self, &node.as_defined_node().expect("kind")),
            Node::ElseNode { .. } => control::else_node(self, &node.as_else_node().expect("kind")),
            Node::EmbeddedStatementsNode { .. } => {
                strings::embedded_statements_node(self, &node.as_embedded_statements_node().expect("kind"))
            }
            Node::EmbeddedVariableNode { .. } => {
                strings::embedded_variable_node(self, &node.as_embedded_variable_node().expect("kind"))
            }
            Node::EnsureNode { .. } => control::ensure_node(self, &node.as_ensure_node().expect("kind")),
            Node::FalseNode { .. } => literals::false_node(self, &node.as_false_node().expect("kind")),
            Node::FindPatternNode { .. } => {
                patterns::find_pattern_node(self, &node.as_find_pattern_node().expect("kind"))
            }
            Node::FlipFlopNode { .. } => control::flip_flop_node(self, &node.as_flip_flop_node().expect("kind")),
            Node::FloatNode { .. } => literals::float_node(self, &node.as_float_node().expect("kind")),
            Node::ForNode { .. } => control::for_node(self, &node.as_for_node().expect("kind")),
            Node::ForwardingArgumentsNode { .. } => {
                calls::forwarding_arguments_node(self, &node.as_forwarding_arguments_node().expect("kind"))
            }
            Node::ForwardingParameterNode { .. } => {
                defs::forwarding_parameter_node(self, &node.as_forwarding_parameter_node().expect("kind"))
            }
            Node::ForwardingSuperNode { .. } => {
                calls::forwarding_super_node(self, &node.as_forwarding_super_node().expect("kind"))
            }
            Node::GlobalVariableAndWriteNode { .. } => {
                assign::global_variable_and_write_node(self, &node.as_global_variable_and_write_node().expect("kind"))
            }
            Node::GlobalVariableOperatorWriteNode { .. } => assign::global_variable_operator_write_node(
                self,
                &node.as_global_variable_operator_write_node().expect("kind"),
            ),
            Node::GlobalVariableOrWriteNode { .. } => {
                assign::global_variable_or_write_node(self, &node.as_global_variable_or_write_node().expect("kind"))
            }
            Node::GlobalVariableReadNode { .. } => {
                literals::global_variable_read_node(self, &node.as_global_variable_read_node().expect("kind"))
            }
            Node::GlobalVariableTargetNode { .. } => {
                assign::global_variable_target_node(self, &node.as_global_variable_target_node().expect("kind"))
            }
            Node::GlobalVariableWriteNode { .. } => {
                assign::global_variable_write_node(self, &node.as_global_variable_write_node().expect("kind"))
            }
            Node::HashNode { .. } => calls::hash_node(self, &node.as_hash_node().expect("kind")),
            Node::HashPatternNode { .. } => {
                patterns::hash_pattern_node(self, &node.as_hash_pattern_node().expect("kind"))
            }
            Node::IfNode { .. } => control::if_node(self, &node.as_if_node().expect("kind")),
            Node::ImaginaryNode { .. } => literals::imaginary_node(self, &node.as_imaginary_node().expect("kind")),
            Node::ImplicitNode { .. } => patterns::implicit_node(self, &node.as_implicit_node().expect("kind")),
            Node::ImplicitRestNode { .. } => {
                patterns::implicit_rest_node(self, &node.as_implicit_rest_node().expect("kind"))
            }
            Node::InNode { .. } => patterns::in_node(self, &node.as_in_node().expect("kind")),
            Node::IndexAndWriteNode { .. } => {
                assign::index_and_write_node(self, &node.as_index_and_write_node().expect("kind"))
            }
            Node::IndexOperatorWriteNode { .. } => {
                assign::index_operator_write_node(self, &node.as_index_operator_write_node().expect("kind"))
            }
            Node::IndexOrWriteNode { .. } => {
                assign::index_or_write_node(self, &node.as_index_or_write_node().expect("kind"))
            }
            Node::IndexTargetNode { .. } => {
                assign::index_target_node(self, &node.as_index_target_node().expect("kind"))
            }
            Node::InstanceVariableAndWriteNode { .. } => assign::instance_variable_and_write_node(
                self,
                &node.as_instance_variable_and_write_node().expect("kind"),
            ),
            Node::InstanceVariableOperatorWriteNode { .. } => assign::instance_variable_operator_write_node(
                self,
                &node.as_instance_variable_operator_write_node().expect("kind"),
            ),
            Node::InstanceVariableOrWriteNode { .. } => {
                assign::instance_variable_or_write_node(self, &node.as_instance_variable_or_write_node().expect("kind"))
            }
            Node::InstanceVariableReadNode { .. } => {
                literals::instance_variable_read_node(self, &node.as_instance_variable_read_node().expect("kind"))
            }
            Node::InstanceVariableTargetNode { .. } => {
                assign::instance_variable_target_node(self, &node.as_instance_variable_target_node().expect("kind"))
            }
            Node::InstanceVariableWriteNode { .. } => {
                assign::instance_variable_write_node(self, &node.as_instance_variable_write_node().expect("kind"))
            }
            Node::IntegerNode { .. } => literals::integer_node(self, &node.as_integer_node().expect("kind")),
            Node::InterpolatedMatchLastLineNode { .. } => strings::interpolated_match_last_line_node(
                self,
                &node.as_interpolated_match_last_line_node().expect("kind"),
            ),
            Node::InterpolatedRegularExpressionNode { .. } => strings::interpolated_regular_expression_node(
                self,
                &node.as_interpolated_regular_expression_node().expect("kind"),
            ),
            Node::InterpolatedStringNode { .. } => {
                strings::interpolated_string_node(self, &node.as_interpolated_string_node().expect("kind"))
            }
            Node::InterpolatedSymbolNode { .. } => {
                strings::interpolated_symbol_node(self, &node.as_interpolated_symbol_node().expect("kind"))
            }
            Node::InterpolatedXStringNode { .. } => {
                strings::interpolated_xstring_node(self, &node.as_interpolated_x_string_node().expect("kind"))
            }
            Node::ItLocalVariableReadNode { .. } => {
                literals::it_local_variable_read_node(self, &node.as_it_local_variable_read_node().expect("kind"))
            }
            Node::ItParametersNode { .. } => {
                defs::it_parameters_node(self, &node.as_it_parameters_node().expect("kind"))
            }
            Node::KeywordHashNode { .. } => calls::keyword_hash_node(self, &node.as_keyword_hash_node().expect("kind")),
            Node::KeywordRestParameterNode { .. } => {
                defs::keyword_rest_parameter_node(self, &node.as_keyword_rest_parameter_node().expect("kind"))
            }
            Node::LambdaNode { .. } => defs::lambda_node(self, &node.as_lambda_node().expect("kind")),
            Node::LocalVariableAndWriteNode { .. } => {
                assign::local_variable_and_write_node(self, &node.as_local_variable_and_write_node().expect("kind"))
            }
            Node::LocalVariableOperatorWriteNode { .. } => assign::local_variable_operator_write_node(
                self,
                &node.as_local_variable_operator_write_node().expect("kind"),
            ),
            Node::LocalVariableOrWriteNode { .. } => {
                assign::local_variable_or_write_node(self, &node.as_local_variable_or_write_node().expect("kind"))
            }
            Node::LocalVariableReadNode { .. } => {
                literals::local_variable_read_node(self, &node.as_local_variable_read_node().expect("kind"))
            }
            Node::LocalVariableTargetNode { .. } => {
                assign::local_variable_target_node(self, &node.as_local_variable_target_node().expect("kind"))
            }
            Node::LocalVariableWriteNode { .. } => {
                assign::local_variable_write_node(self, &node.as_local_variable_write_node().expect("kind"))
            }
            Node::MatchLastLineNode { .. } => {
                strings::match_last_line_node(self, &node.as_match_last_line_node().expect("kind"))
            }
            Node::MatchPredicateNode { .. } => {
                patterns::match_predicate_node(self, &node.as_match_predicate_node().expect("kind"))
            }
            Node::MatchRequiredNode { .. } => {
                patterns::match_required_node(self, &node.as_match_required_node().expect("kind"))
            }
            Node::MatchWriteNode { .. } => patterns::match_write_node(self, &node.as_match_write_node().expect("kind")),
            Node::ModuleNode { .. } => defs::module_node(self, &node.as_module_node().expect("kind")),
            Node::MultiTargetNode { .. } => {
                assign::multi_target_node(self, &node.as_multi_target_node().expect("kind"))
            }
            Node::MultiWriteNode { .. } => assign::multi_write_node(self, &node.as_multi_write_node().expect("kind")),
            Node::NextNode { .. } => control::next_node(self, &node.as_next_node().expect("kind")),
            Node::NilNode { .. } => literals::nil_node(self, &node.as_nil_node().expect("kind")),
            Node::NoKeywordsParameterNode { .. } => {
                defs::no_keywords_parameter_node(self, &node.as_no_keywords_parameter_node().expect("kind"))
            }
            Node::NumberedParametersNode { .. } => {
                defs::numbered_parameters_node(self, &node.as_numbered_parameters_node().expect("kind"))
            }
            Node::NumberedReferenceReadNode { .. } => {
                literals::numbered_reference_read_node(self, &node.as_numbered_reference_read_node().expect("kind"))
            }
            Node::OptionalKeywordParameterNode { .. } => {
                defs::optional_keyword_parameter_node(self, &node.as_optional_keyword_parameter_node().expect("kind"))
            }
            Node::OptionalParameterNode { .. } => {
                defs::optional_parameter_node(self, &node.as_optional_parameter_node().expect("kind"))
            }
            Node::OrNode { .. } => control::or_node(self, &node.as_or_node().expect("kind")),
            Node::ParametersNode { .. } => defs::parameters_node(self, &node.as_parameters_node().expect("kind")),
            Node::ParenthesesNode { .. } => control::parentheses_node(self, &node.as_parentheses_node().expect("kind")),
            Node::PinnedExpressionNode { .. } => {
                patterns::pinned_expression_node(self, &node.as_pinned_expression_node().expect("kind"))
            }
            Node::PinnedVariableNode { .. } => {
                patterns::pinned_variable_node(self, &node.as_pinned_variable_node().expect("kind"))
            }
            Node::PostExecutionNode { .. } => {
                control::post_execution_node(self, &node.as_post_execution_node().expect("kind"))
            }
            Node::PreExecutionNode { .. } => {
                control::pre_execution_node(self, &node.as_pre_execution_node().expect("kind"))
            }
            Node::RangeNode { .. } => literals::range_node(self, &node.as_range_node().expect("kind")),
            Node::RationalNode { .. } => literals::rational_node(self, &node.as_rational_node().expect("kind")),
            Node::RedoNode { .. } => control::redo_node(self, &node.as_redo_node().expect("kind")),
            Node::RegularExpressionNode { .. } => {
                strings::regular_expression_node(self, &node.as_regular_expression_node().expect("kind"))
            }
            Node::RequiredKeywordParameterNode { .. } => {
                defs::required_keyword_parameter_node(self, &node.as_required_keyword_parameter_node().expect("kind"))
            }
            Node::RequiredParameterNode { .. } => {
                defs::required_parameter_node(self, &node.as_required_parameter_node().expect("kind"))
            }
            Node::RescueModifierNode { .. } => {
                control::rescue_modifier_node(self, &node.as_rescue_modifier_node().expect("kind"))
            }
            Node::RescueNode { .. } => control::rescue_node(self, &node.as_rescue_node().expect("kind")),
            Node::RestParameterNode { .. } => {
                defs::rest_parameter_node(self, &node.as_rest_parameter_node().expect("kind"))
            }
            Node::RetryNode { .. } => control::retry_node(self, &node.as_retry_node().expect("kind")),
            Node::ReturnNode { .. } => control::return_node(self, &node.as_return_node().expect("kind")),
            Node::SelfNode { .. } => literals::self_node(self, &node.as_self_node().expect("kind")),
            Node::ShareableConstantNode { .. } => {
                literals::shareable_constant_node(self, &node.as_shareable_constant_node().expect("kind"))
            }
            Node::SingletonClassNode { .. } => {
                defs::singleton_class_node(self, &node.as_singleton_class_node().expect("kind"))
            }
            Node::SourceEncodingNode { .. } => {
                literals::source_encoding_node(self, &node.as_source_encoding_node().expect("kind"))
            }
            Node::SourceFileNode { .. } => literals::source_file_node(self, &node.as_source_file_node().expect("kind")),
            Node::SourceLineNode { .. } => literals::source_line_node(self, &node.as_source_line_node().expect("kind")),
            Node::SplatNode { .. } => calls::splat_node(self, &node.as_splat_node().expect("kind")),
            Node::StringNode { .. } => strings::string_node(self, &node.as_string_node().expect("kind")),
            Node::SuperNode { .. } => calls::super_node(self, &node.as_super_node().expect("kind")),
            Node::SymbolNode { .. } => strings::symbol_node(self, &node.as_symbol_node().expect("kind")),
            Node::TrueNode { .. } => literals::true_node(self, &node.as_true_node().expect("kind")),
            Node::UndefNode { .. } => defs::undef_node(self, &node.as_undef_node().expect("kind")),
            Node::UnlessNode { .. } => control::unless_node(self, &node.as_unless_node().expect("kind")),
            Node::UntilNode { .. } => control::until_node(self, &node.as_until_node().expect("kind")),
            Node::WhenNode { .. } => control::when_node(self, &node.as_when_node().expect("kind")),
            Node::WhileNode { .. } => control::while_node(self, &node.as_while_node().expect("kind")),
            Node::XStringNode { .. } => strings::xstring_node(self, &node.as_x_string_node().expect("kind")),
            Node::YieldNode { .. } => calls::yield_node(self, &node.as_yield_node().expect("kind")),
        }
    }
}
